# Generated by Django 5.2.dev20241210101609 on 2024-12-10 13:24

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="item",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "description", config="english"
                ),
                name="search_vector_idx",
            ),
        ),
    ]
