# Generated by Django 4.2.20 on 2025-04-02 09:53

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import paradedb.indexes


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0002_item_search_vector_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=512)),
                ("isbn", models.CharField(blank=True, max_length=14)),
                ("average_rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("ratings_count", models.IntegerField()),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField()),
                ("image_url", models.URLField()),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("publication_year", models.IntegerField()),
                ("ext_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ("-pk",),
                "indexes": [
                    paradedb.indexes.BM25Index(
                        fields=["title", "isbn", "description", "publication_year"],
                        name="book_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.search.SearchVector(
                            "title", "isbn", "description", config="english"
                        ),
                        name="book_search_vector_idx",
                    ),
                ],
            },
        ),
    ]
