# Generated by Django 4.2.20 on 2025-04-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0003_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
