# Generated by Django 4.2.20 on 2025-04-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0004_alter_book_publication_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="average_rating",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=3, null=True
            ),
        ),
    ]
