# Generated by Django 4.2.20 on 2025-04-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0005_alter_book_average_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="image_url",
            field=models.URLField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="book",
            name="url",
            field=models.URLField(max_length=1024),
        ),
    ]
