# Generated by Django 4.2.20 on 2025-04-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0006_alter_book_image_url_alter_book_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
