# Generated by Django 4.2.20 on 2025-04-02 11:47

from django.db import migrations, models
import django.db.models.deletion
import paradedb.indexes


class Migration(migrations.Migration):
    dependencies = [
        ("testapp", "0007_alter_book_isbn"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added", models.DateTimeField(auto_now_add=True)),
                ("review", models.TextField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.book"
                    ),
                ),
            ],
            options={
                "verbose_name": "Book Review",
                "verbose_name_plural": "Book Reviews",
                "ordering": ["-added"],
                "indexes": [
                    paradedb.indexes.BM25Index(
                        fields=["review"], name="book_review_idx"
                    )
                ],
            },
        ),
    ]
