# Generated by Django 5.1.6 on 2025-04-06 12:34

from django.db import migrations
import django

class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0009_remove_book_book_search_vector_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="book",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["vector_column"], name="book_search_vector_idx"
            ),
        ),
    ]
